name: build

on: [push]

jobs:
  # eslint:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@master
  #   - name: yarn install
  #     run: yarn install
  #   - name: lint
  #     run: yarn run lint

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command
        registry-url: registry.npmjs.org
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: generate
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: deploy
