name: build

on: [push]

jobs:
  # eslint:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@master
  #   - name: yarn install
  #     run: yarn install
  #   - name: lint
  #     run: yarn run lint

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: yarn install
      run: yarn install
    - name: generate
      run: yarn run generate
    - name: deploy
      run: yarn run deploy
